import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const mePage = readFileSync(new URL('../page.tsx', import.meta.url), 'utf8')
const overviewPage = readFileSync(new URL('./page.tsx', import.meta.url), 'utf8')
const chapterPage = readFileSync(new URL('./chapters/[chapterId]/page.tsx', import.meta.url), 'utf8')
const sliderSource = readFileSync(new URL('./chapters/[chapterId]/score-slider.tsx', import.meta.url), 'utf8')
const actionsSource = readFileSync(new URL('./actions.ts', import.meta.url), 'utf8')
const apiSource = readFileSync(new URL('../../../lib/api.ts', import.meta.url), 'utf8')

test('me page opens the awareness check tool instead of showing a planning card', () => {
  assert.equal(mePage.includes('意识强度检测'), true)
  assert.equal(mePage.includes('href: "/me/awareness-check"'), true)
  assert.equal(mePage.includes('开始检测'), true)
  assert.equal(mePage.includes('查看规划'), false)
})

test('awareness check overview reads current check and trends from the API', () => {
  assert.equal(overviewPage.includes('getAwarenessCheckCurrent'), true)
  assert.equal(overviewPage.includes('getAwarenessCheckTrends'), true)
  assert.equal(overviewPage.includes('清空未提交草稿'), true)
  assert.equal(overviewPage.includes('选择章节'), true)
  assert.equal(overviewPage.includes('最近单章记录'), false)
  assert.equal(overviewPage.includes('综合结果'), true)
  assert.equal(overviewPage.includes('尚未生成'), true)
  assert.equal(overviewPage.includes('综合趋势'), true)
  assert.equal(overviewPage.includes('再次检测'), true)
  assert.equal(overviewPage.includes('function MobileChapterTile('), true)
  assert.equal(overviewPage.includes('grid grid-cols-3 gap-2 md:hidden'), true)
  assert.equal(overviewPage.includes('hidden gap-3 md:grid md:grid-cols-3'), true)
  assert.equal(overviewPage.includes('aria-label={`第 ${chapter.chapterNo} 章'), true)
  assert.equal(apiSource.includes('/awareness-checks/current'), true)
  assert.equal(apiSource.includes('/awareness-checks/trends'), true)
  assert.equal(apiSource.includes('hasPrevScore: boolean'), true)
})

test('single chapter awareness check page uses sliders and server actions', () => {
  assert.equal(chapterPage.includes('getAwarenessCheckChapter'), true)
  assert.equal(chapterPage.includes('getAwarenessCheckTrends'), true)
  assert.equal(chapterPage.includes('<ScoreSlider point={point} />'), true)
  assert.equal(chapterPage.includes('本章历史'), true)
  assert.equal(chapterPage.includes('历次得分'), true)
  assert.equal(chapterPage.includes('max-w-[680px]'), true)
  assert.equal(chapterPage.includes('w-10 max-w-full'), true)
  assert.equal(chapterPage.includes('const isLatest = index === visible.length - 1'), true)
  assert.equal(chapterPage.includes('const trendPoints = visible.map'), true)
  assert.equal(chapterPage.includes('<svg className="pointer-events-none'), true)
  assert.equal(chapterPage.includes('id="history-trend-gradient"'), true)
  assert.equal(chapterPage.includes('url(#history-trend-gradient)'), true)
  assert.equal(chapterPage.includes('bg-[linear-gradient(180deg,#7bc5c2_0%,#79a6d5_100%)]'), true)
  assert.equal(chapterPage.includes('折线展示最近记录的变化趋势'), true)
  assert.equal(chapterPage.includes('history.length - visible.length + index + 1'), false)
  assert.equal(chapterPage.includes('aria-label="本章历次检测评分柱状图与趋势折线，柱内显示分数，柱下显示提交时间"'), true)
  assert.equal(chapterPage.includes('splitSubmittedAt'), true)
  assert.equal(chapterPage.includes('recentRecordLimit'), false)
  assert.equal(chapterPage.includes('最近 3 次记录'), false)
  assert.equal(chapterPage.includes('slice(-5)'), false)
  assert.equal(chapterPage.includes('chapterHistory'), true)
  assert.equal(chapterPage.includes('&larr;'), true)
  assert.equal(chapterPage.includes('返回检测总览'), true)
  assert.equal(chapterPage.includes('bg-white/88'), true)
  assert.equal(chapterPage.includes('label="已评分"'), true)
  assert.equal(chapterPage.includes('保存本章评分'), true)
  assert.equal(chapterPage.includes('提交本章检测'), true)
  assert.equal(chapterPage.includes('提交本章新评分'), true)
  assert.equal(chapterPage.includes('本章已提交'), false)
  assert.equal(chapterPage.includes('回到总览查看'), false)
  assert.equal(sliderSource.includes("type=\"range\""), true)
  assert.equal(sliderSource.includes("value={selfScore}"), true)
  assert.equal(actionsSource.includes('saveAwarenessCheckChapterScores'), true)
  assert.equal(actionsSource.includes('submitAwarenessCheckChapter'), true)
})
